version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER:-root}
      - DB_PASS=${DB_PASS:-}
      - DB_NAME=${DB_NAME:-nissan_tickets}
      - UPLOAD_PATH=${UPLOAD_PATH:-uploads/}
      - UPLOAD_DRIVER=${UPLOAD_DRIVER:-local}
      - APP_ENV=${APP_ENV:-production}
      - APP_DEBUG=${APP_DEBUG:-false}
    volumes:
      - ./uploads:/var/www/html/uploads
      - ./logs:/var/log
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-}
      - MYSQL_DATABASE=${DB_NAME:-nissan_tickets}
      - MYSQL_USER=${DB_USER:-root}
      - MYSQL_PASSWORD=${DB_PASS:-}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./nissan_tickets.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - ./uploads:/var/www/html/uploads
    depends_on:
      - app
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data: 